// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Sidebar principal con introducción
  mainSidebar: [
    'intro',
  ],
  
  // Sidebar para cada tema - autogenerado desde las carpetas
  tema01Sidebar: [{type: 'autogenerated', dirName: 'tema-01-fundamentos'}],
  tema02Sidebar: [{type: 'autogenerated', dirName: 'tema-02-seguridad-activa'}],
  tema03Sidebar: [{type: 'autogenerated', dirName: 'tema-03-seguridad-perimetral'}],
  tema04Sidebar: [{type: 'autogenerated', dirName: 'tema-04-firewalls-proxy'}],
  tema05Sidebar: [{type: 'autogenerated', dirName: 'tema-05-alta-disponibilidad'}],
  tema06Sidebar: [{type: 'autogenerated', dirName: 'tema-06-ciberseguridad-auditorias'}],
};

export default sidebars;
